name: Update Data

on:
    push:
        branches:
            - main

jobs:
    update-data:
        runs-on: ubuntu-latest

        environment: prod

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set Up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'			
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Update DB
              env:
                IH_URL: ${{ vars.IH_URL }}
                IH_KEY: ${{ vars.IH_KEY }}
                TTH_URL: ${{ vars.TTH_URL }}
                TTH_KEY: ${{ vars.TTH_KEY }}
                BKT_URL: ${{ vars.BKT_URL }}
                BKT_KEY: ${{ vars.BKT_KEY }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_URI: ${{ secrets.DB_URI }}
                COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
              run: |
                python src/main.py --output="output.json"